version: '3.8'
services:
  db:
    build:
      context: ./Database
    image: postgres:smart_fridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: smart_fridge
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Ensure this is correct

  processor:
    restart: always
    build:
      context: ./Data-process
    depends_on:
      - db
    environment:
      DB_HOST: db  # Use the service name instead of localhost
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: smart_fridge
    volumes:
      - ./Data-process:/app  # Mount the directory to access scripts and files inside the container