version: '3.8'

services:
  db:
    build: ./Database
    image: postgres:smart_fridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: smart_fridge
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  processor:
    restart: always
    build: ./Data-process
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: smart_fridge
    volumes:
      - ./Data-process:/app

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

  app:
    build: .
    command: python main.py
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: smart_fridge
    volumes:
      - .:/app  # Mount the current directory to access main.py inside the container

volumes:
  pgadmin-data: